name: First-time Contributor Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  greet-first-time-pr:
    name: Greet First-Time PR Contributors
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' && github.event.pull_request.head.repo.fork
    steps:
      - name: Check for first-time PR contributor
        uses: actions/github-script@v7
        with:
          script: |
            const author = context.actor;
            const { owner, repo } = context.repo;
            
            const prTitle = context.payload.pull_request.title;

            console.log(`Checking for past PRs from ${author}...`);
            const allIssues = await github.paginate(github.rest.issues.listForRepo, {
              owner,
              repo,
              creator: author,
              state: 'all'
            });

            const prs = allIssues.filter(issue => issue.pull_request);
            const prCount = prs.length;

            console.log(`Found ${prCount} PR(s) from ${author}.`);
            console.log(`PR Title is: "${prTitle}"`);

            if (prCount === 1 || prTitle.includes('[FORCE GREETING]')) {
              if (prTitle.includes('[FORCE GREETING]')) {
                console.log('Forcing greeting due to "[FORCE GREETING]" in title.');
              } else {
                console.log('This is the first PR. Posting a welcome comment.');
              }
            
              const prMessage = `
              ### Hey @${author}! 🎉
            
              Thanks for opening your first pull request. We really appreciate it.
            
              👉 Please confirm by writing this comment that your contribution and following ones comply with the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0) and the [Code of Conduct](https://github.com/operaton/operaton/blob/main/CODE_OF_CONDUCT.md):
              \`\`\`
              I confirm that my contribution and following ones comply with the Apache License 2.0 and the Code of Conduct.
              \`\`\`
              Consider adding a star ⭐️ to the [repository](https://github.com/operaton/operaton) if you like it, we appreciate that.
            
              Contributors will be added to the release notes of the next release.
              `;

              await github.rest.issues.createComment({
                owner: owner,
                repo: repo,
                issue_number: context.issue.number,
                body: prMessage
              });
            }